// Generated by the Crawlora platform client generator. Do not edit.
export const operations = {
  "youtube-captions": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-captions",
    "method": "GET",
    "path": "/youtube/captions/{id}",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "lang",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "youtube-channel-playlists": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-channel-playlists",
    "method": "GET",
    "path": "/youtube/channel/{id}/playlists",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "continuation_token",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "youtube-channel-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-channel-search",
    "method": "GET",
    "path": "/youtube/channel/{id}/search",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "q",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "continuation_token",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "youtube-channel-shorts": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-channel-shorts",
    "method": "GET",
    "path": "/youtube/channel/{id}/shorts",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "youtube-channel-videos": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-channel-videos",
    "method": "GET",
    "path": "/youtube/channel/{id}/videos",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "continuation_token",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "youtube-comments": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-comments",
    "method": "GET",
    "path": "/youtube/comments/{id}",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "continuation_token",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "youtube-playlist": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-playlist",
    "method": "GET",
    "path": "/youtube/playlist/{id}",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "continuation_token",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "youtube-profile": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-profile",
    "method": "GET",
    "path": "/youtube/profile/{id}",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "youtube-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-search",
    "method": "GET",
    "path": "/youtube/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "q",
        "type": "string"
      },
      {
        "in": "query",
        "name": "search_query",
        "type": "string"
      },
      {
        "in": "query",
        "name": "continuation_token",
        "type": "string"
      },
      {
        "enum": [
          "video",
          "shorts",
          "channel",
          "playlist",
          "movie"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      },
      {
        "enum": [
          "relevance",
          "upload_date",
          "view_count",
          "popularity",
          "rating"
        ],
        "in": "query",
        "name": "sort_by",
        "type": "string"
      },
      {
        "enum": [
          "last_hour",
          "today",
          "this_week",
          "this_month",
          "this_year"
        ],
        "in": "query",
        "name": "upload_date",
        "type": "string"
      },
      {
        "enum": [
          "under_3_minutes",
          "three_to_20_minutes",
          "over_20_minutes",
          "under_3",
          "three_to_20",
          "over_20",
          "short",
          "medium",
          "long"
        ],
        "in": "query",
        "name": "duration",
        "type": "string"
      },
      {
        "in": "query",
        "name": "features",
        "type": "string"
      },
      {
        "in": "query",
        "name": "hl",
        "type": "string"
      },
      {
        "in": "query",
        "name": "gl",
        "type": "string"
      },
      {
        "in": "query",
        "name": "params",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "youtube-suggest": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-suggest",
    "method": "GET",
    "path": "/youtube/suggest",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "q",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "count",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "hl",
        "type": "string"
      },
      {
        "in": "query",
        "name": "gl",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "youtube-tag": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-tag",
    "method": "GET",
    "path": "/youtube/tag/{tag}",
    "pathParams": [
      "tag"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "all",
          "shorts"
        ],
        "in": "query",
        "name": "type",
        "type": "string"
      },
      {
        "in": "query",
        "name": "continuation_token",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "youtube-transcript": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-transcript",
    "method": "GET",
    "path": "/youtube/transcript/{id}",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json",
      "text/plain"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "lang",
        "type": "string"
      },
      {
        "in": "query",
        "name": "translate_to",
        "type": "string"
      },
      {
        "enum": [
          "json",
          "text",
          "srt",
          "vtt"
        ],
        "in": "query",
        "name": "format",
        "type": "string"
      },
      {
        "in": "query",
        "name": "timestamps",
        "type": "boolean"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "youtube-transcript-languages": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-transcript-languages",
    "method": "GET",
    "path": "/youtube/transcript/{id}/languages",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "youtube-video": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "youtube-video",
    "method": "GET",
    "path": "/youtube/video/{id}",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  }
};

export const groups = {
  "youtube": {
    "captions": "youtube-captions",
    "channelPlaylists": "youtube-channel-playlists",
    "channelSearch": "youtube-channel-search",
    "channelShorts": "youtube-channel-shorts",
    "channelVideos": "youtube-channel-videos",
    "comments": "youtube-comments",
    "playlist": "youtube-playlist",
    "profile": "youtube-profile",
    "search": "youtube-search",
    "suggest": "youtube-suggest",
    "tag": "youtube-tag",
    "transcript": "youtube-transcript",
    "transcriptLanguages": "youtube-transcript-languages",
    "video": "youtube-video"
  }
};

export const operationCount = 14;

export const OperationIds = Object.freeze({
  "YoutubeCaptions": "youtube-captions",
  "YoutubeChannelPlaylists": "youtube-channel-playlists",
  "YoutubeChannelSearch": "youtube-channel-search",
  "YoutubeChannelShorts": "youtube-channel-shorts",
  "YoutubeChannelVideos": "youtube-channel-videos",
  "YoutubeComments": "youtube-comments",
  "YoutubePlaylist": "youtube-playlist",
  "YoutubeProfile": "youtube-profile",
  "YoutubeSearch": "youtube-search",
  "YoutubeSuggest": "youtube-suggest",
  "YoutubeTag": "youtube-tag",
  "YoutubeTranscript": "youtube-transcript",
  "YoutubeTranscriptLanguages": "youtube-transcript-languages",
  "YoutubeVideo": "youtube-video"
});
