// Generated by scripts/generate.py. Do not edit manually.

export type CrawloraResponse<T = unknown> = T;
export type CrawloraBody<T = Record<string, unknown>> = T;

export interface ModelAppResponse {
  "code"?: number;
  "data"?: unknown;
  "msg"?: unknown;
}

export interface ModelYoutubeVideoResponseDoc {
  "code"?: number;
  "data"?: ModelYoutubeVideoDetail;
  "msg"?: string;
}

export interface ModelYoutubeVideoDetail {
  "channel_id"?: string;
  "channel_title"?: string;
  "comments_count"?: number;
  "description"?: string;
  "dislikes_count"?: number;
  "duration_seconds"?: number;
  "id"?: string;
  "likes_count"?: number;
  "published_at"?: string;
  "title"?: string;
  "views_count"?: number;
}

export interface ModelYoutubeTranscriptLanguagesResponseDoc {
  "code"?: number;
  "data"?: Array<ModelYoutubeTranscriptLanguage>;
  "msg"?: string;
}

export interface ModelYoutubeTranscriptLanguage {
  "is_generated"?: boolean;
  "is_translatable"?: boolean;
  "language"?: string;
  "language_code"?: string;
}

export interface ModelYoutubeTranscriptResponseDoc {
  "code"?: number;
  "data"?: ModelYoutubeTranscriptResponse;
  "msg"?: string;
}

export interface ModelYoutubeTranscriptResponse {
  "is_generated"?: boolean;
  "language"?: string;
  "language_code"?: string;
  "segments"?: Array<ModelYoutubeTranscriptSegment>;
  "text"?: string;
  "translation_language"?: string;
  "video_id"?: string;
}

export interface ModelYoutubeTranscriptSegment {
  "duration"?: number;
  "start"?: number;
  "text"?: string;
}

export interface ModelYoutubeTagResponseDoc {
  "code"?: number;
  "data"?: ModelYoutubeTagResp;
  "msg"?: string;
}

export interface ModelYoutubeTagResp {
  "continuation_token"?: string;
  "meta"?: ModelYoutubeTagMeta;
  "videos"?: Array<ModelYoutubeVideoDetail>;
}

export interface ModelYoutubeTagMeta {
  "channelsCount"?: number;
  "videosCount"?: number;
}

export interface ModelYoutubeSuggestResponseDoc {
  "code"?: number;
  "data"?: ModelSuggestResponse;
  "msg"?: string;
}

export interface ModelSuggestResponse {
  "query"?: string;
  "suggestions"?: Array<ModelSuggestSuggestion>;
}

export interface ModelSuggestSuggestion {
  "position"?: number;
  "query"?: string;
}

export interface ModelYoutubeSearchResponseDoc {
  "code"?: number;
  "data"?: ModelYoutubeSearchResponse;
  "msg"?: string;
}

export interface ModelYoutubeSearchResponse {
  "continuation_token"?: string;
  "estimated_results"?: number;
  "items"?: Array<ModelYoutubeSearchItem>;
  "query"?: string;
}

export interface ModelYoutubeSearchItem {
  "badges"?: Array<string>;
  "channel_id"?: string;
  "channel_thumbnail"?: string;
  "channel_title"?: string;
  "description_snippet"?: string;
  "duration"?: string;
  "duration_seconds"?: number;
  "handle"?: string;
  "is_live"?: boolean;
  "is_short"?: boolean;
  "is_verified"?: boolean;
  "playlist_id"?: string;
  "position"?: number;
  "published_text"?: string;
  "short_view_count"?: string;
  "subscriber_count"?: string;
  "thumbnail"?: string;
  "title"?: string;
  "type"?: string;
  "url"?: string;
  "video_count"?: string;
  "video_id"?: string;
  "view_count"?: string;
}

export interface ModelYoutubeProfileResponseDoc {
  "code"?: number;
  "data"?: ModelYoutubeProfile;
  "msg"?: string;
}

export interface ModelYoutubeProfile {
  "bio"?: string;
  "channel_id"?: string;
  "channel_name"?: string;
  "channel_url"?: string;
  "created_at"?: string;
  "id"?: string;
  "joined_date"?: string;
  "links"?: Array<string>;
  "profile_pic"?: string;
  "region"?: string;
  "stats"?: ModelYoutubeProfileStats;
  "updated_at"?: string;
}

export interface ModelYoutubeProfileStats {
  "followers_count"?: number;
  "videos_count"?: number;
  "views_count"?: number;
}

export interface ModelYoutubePlaylistResponseDoc {
  "code"?: number;
  "data"?: ModelYoutubePlaylistResponse;
  "msg"?: string;
}

export interface ModelYoutubePlaylistResponse {
  "channel_id"?: string;
  "channel_title"?: string;
  "continuation_token"?: string;
  "items"?: Array<ModelYoutubeSearchItem>;
  "playlist_id"?: string;
  "thumbnail"?: string;
  "title"?: string;
  "url"?: string;
  "video_count"?: string;
}

export interface ModelYoutubeCommentsResponseDoc {
  "code"?: number;
  "data"?: ModelYoutubeCommentResponse;
  "msg"?: string;
}

export interface ModelYoutubeCommentResponse {
  "comments"?: Array<ModelYoutubeComment>;
  "continuation_token"?: string;
}

export interface ModelYoutubeComment {
  "channel_id"?: string;
  "comment_id"?: string;
  "content"?: string;
  "continuation_token"?: string;
  "likes_count"?: number;
  "published_time"?: string;
  "reply_count"?: number;
  "user_name"?: string;
}

export interface ModelYoutubeChannelFeedResponseDoc {
  "code"?: number;
  "data"?: ModelYoutubeChannelFeedResponse;
  "msg"?: string;
}

export interface ModelYoutubeChannelFeedResponse {
  "channel_id"?: string;
  "channel_title"?: string;
  "channel_url"?: string;
  "continuation_token"?: string;
  "handle"?: string;
  "items"?: Array<ModelYoutubeSearchItem>;
  "query"?: string;
  "thumbnail"?: string;
}

export interface ModelYoutubeChannelShortsResponseDoc {
  "code"?: number;
  "data"?: ModelYoutubeChannelShortsResponse;
  "msg"?: string;
}

export interface ModelYoutubeChannelShortsResponse {
  "channel_id"?: string;
  "channel_title"?: string;
  "channel_url"?: string;
  "handle"?: string;
  "shorts"?: Array<ModelYoutubeChannelShort>;
  "thumbnail"?: string;
}

export interface ModelYoutubeChannelShort {
  "position"?: number;
  "thumbnail"?: string;
  "title"?: string;
  "url"?: string;
  "video_id"?: string;
  "view_count"?: string;
}

export interface ModelYoutubeChannelSearchResponseDoc {
  "code"?: number;
  "data"?: ModelYoutubeChannelSearchResponseDataDoc;
  "msg"?: string;
}

export interface ModelYoutubeChannelSearchResponseDataDoc {
  "channel_id"?: string;
  "channel_title"?: string;
  "channel_url"?: string;
  "continuation_token"?: string;
  "handle"?: string;
  "items"?: Array<ModelYoutubeSearchItem>;
  "query"?: string;
  "thumbnail"?: string;
}

export interface ModelYoutubeCaptionsResponseDoc {
  "code"?: number;
  "data"?: Array<ModelYoutubeCaption>;
  "msg"?: string;
}

export interface ModelYoutubeCaption {
  "duration"?: number;
  "start"?: number;
  "text"?: string;
}

export type YoutubeCaptionsResponse = CrawloraResponse<ModelYoutubeCaptionsResponseDoc>;
export interface YoutubeCaptionsParams {
  "id": string;
  "lang"?: string;
}

export type YoutubeChannelPlaylistsResponse = CrawloraResponse<ModelYoutubeChannelFeedResponseDoc>;
export interface YoutubeChannelPlaylistsParams {
  "id": string;
  "continuation_token"?: string;
}

export type YoutubeChannelSearchResponse = CrawloraResponse<ModelYoutubeChannelSearchResponseDoc>;
export interface YoutubeChannelSearchParams {
  "id": string;
  "q": string;
  "continuation_token"?: string;
}

export type YoutubeChannelShortsResponse = CrawloraResponse<ModelYoutubeChannelShortsResponseDoc>;
export interface YoutubeChannelShortsParams {
  "id": string;
}

export type YoutubeChannelVideosResponse = CrawloraResponse<ModelYoutubeChannelFeedResponseDoc>;
export interface YoutubeChannelVideosParams {
  "id": string;
  "continuation_token"?: string;
}

export type YoutubeCommentsResponse = CrawloraResponse<ModelYoutubeCommentsResponseDoc>;
export interface YoutubeCommentsParams {
  "id": string;
  "continuation_token"?: string;
}

export type YoutubePlaylistResponse = CrawloraResponse<ModelYoutubePlaylistResponseDoc>;
export interface YoutubePlaylistParams {
  "id": string;
  "continuation_token"?: string;
}

export type YoutubeProfileResponse = CrawloraResponse<ModelYoutubeProfileResponseDoc>;
export interface YoutubeProfileParams {
  "id": string;
}

export type YoutubeSearchResponse = CrawloraResponse<ModelYoutubeSearchResponseDoc>;
export interface YoutubeSearchParams {
  "q"?: string;
  "search_query"?: string;
  "continuation_token"?: string;
  "type"?: "video" | "shorts" | "channel" | "playlist" | "movie";
  "sort_by"?: "relevance" | "upload_date" | "view_count" | "popularity" | "rating";
  "upload_date"?: "last_hour" | "today" | "this_week" | "this_month" | "this_year";
  "duration"?: "under_3_minutes" | "three_to_20_minutes" | "over_20_minutes" | "under_3" | "three_to_20" | "over_20" | "short" | "medium" | "long";
  "features"?: string;
  "hl"?: string;
  "gl"?: string;
  "params"?: string;
}

export type YoutubeSuggestResponse = CrawloraResponse<ModelYoutubeSuggestResponseDoc>;
export interface YoutubeSuggestParams {
  "q": string;
  "count"?: number;
  "hl"?: string;
  "gl"?: string;
}

export type YoutubeTagResponse = CrawloraResponse<ModelYoutubeTagResponseDoc>;
export interface YoutubeTagParams {
  "tag": string;
  "type"?: "all" | "shorts";
  "continuation_token"?: string;
}

export type YoutubeTranscriptResponse = CrawloraResponse<ModelYoutubeTranscriptResponseDoc>;
export interface YoutubeTranscriptParams {
  "id": string;
  "lang"?: string;
  "translate_to"?: string;
  "format"?: "json" | "text" | "srt" | "vtt";
  "timestamps"?: boolean;
}

export type YoutubeTranscriptLanguagesResponse = CrawloraResponse<ModelYoutubeTranscriptLanguagesResponseDoc>;
export interface YoutubeTranscriptLanguagesParams {
  "id": string;
}

export type YoutubeVideoResponse = CrawloraResponse<ModelYoutubeVideoResponseDoc>;
export interface YoutubeVideoParams {
  "id": string;
}

export interface YoutubeService {
  captions<T = YoutubeCaptionsResponse>(params: YoutubeCaptionsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  channelPlaylists<T = YoutubeChannelPlaylistsResponse>(params: YoutubeChannelPlaylistsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  channelSearch<T = YoutubeChannelSearchResponse>(params: YoutubeChannelSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  channelShorts<T = YoutubeChannelShortsResponse>(params: YoutubeChannelShortsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  channelVideos<T = YoutubeChannelVideosResponse>(params: YoutubeChannelVideosParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  comments<T = YoutubeCommentsResponse>(params: YoutubeCommentsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  playlist<T = YoutubePlaylistResponse>(params: YoutubePlaylistParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  profile<T = YoutubeProfileResponse>(params: YoutubeProfileParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  search<T = YoutubeSearchResponse>(params?: YoutubeSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  suggest<T = YoutubeSuggestResponse>(params: YoutubeSuggestParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  tag<T = YoutubeTagResponse>(params: YoutubeTagParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  transcript<T = YoutubeTranscriptResponse>(params: YoutubeTranscriptParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  transcriptLanguages<T = YoutubeTranscriptLanguagesResponse>(params: YoutubeTranscriptLanguagesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  video<T = YoutubeVideoResponse>(params: YoutubeVideoParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
}

export interface CrawloraGeneratedGroups {
  youtube: YoutubeService;
}

export interface OperationParamsMap {
  "youtube-captions": YoutubeCaptionsParams;
  "youtube-channel-playlists": YoutubeChannelPlaylistsParams;
  "youtube-channel-search": YoutubeChannelSearchParams;
  "youtube-channel-shorts": YoutubeChannelShortsParams;
  "youtube-channel-videos": YoutubeChannelVideosParams;
  "youtube-comments": YoutubeCommentsParams;
  "youtube-playlist": YoutubePlaylistParams;
  "youtube-profile": YoutubeProfileParams;
  "youtube-search": YoutubeSearchParams;
  "youtube-suggest": YoutubeSuggestParams;
  "youtube-tag": YoutubeTagParams;
  "youtube-transcript": YoutubeTranscriptParams;
  "youtube-transcript-languages": YoutubeTranscriptLanguagesParams;
  "youtube-video": YoutubeVideoParams;
}

export interface OperationResponseMap {
  "youtube-captions": YoutubeCaptionsResponse;
  "youtube-channel-playlists": YoutubeChannelPlaylistsResponse;
  "youtube-channel-search": YoutubeChannelSearchResponse;
  "youtube-channel-shorts": YoutubeChannelShortsResponse;
  "youtube-channel-videos": YoutubeChannelVideosResponse;
  "youtube-comments": YoutubeCommentsResponse;
  "youtube-playlist": YoutubePlaylistResponse;
  "youtube-profile": YoutubeProfileResponse;
  "youtube-search": YoutubeSearchResponse;
  "youtube-suggest": YoutubeSuggestResponse;
  "youtube-tag": YoutubeTagResponse;
  "youtube-transcript": YoutubeTranscriptResponse;
  "youtube-transcript-languages": YoutubeTranscriptLanguagesResponse;
  "youtube-video": YoutubeVideoResponse;
}

export interface OperationRequiredParamsMap {
  "youtube-captions": true;
  "youtube-channel-playlists": true;
  "youtube-channel-search": true;
  "youtube-channel-shorts": true;
  "youtube-channel-videos": true;
  "youtube-comments": true;
  "youtube-playlist": true;
  "youtube-profile": true;
  "youtube-search": false;
  "youtube-suggest": true;
  "youtube-tag": true;
  "youtube-transcript": true;
  "youtube-transcript-languages": true;
  "youtube-video": true;
}

export type OperationId = keyof OperationParamsMap;

export type OperationRequestArgs<I extends OperationId> =
  OperationRequiredParamsMap[I] extends true
    ? [params: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions]
    : [params?: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions];

export type OperationIdLiteral =
  | "youtube-captions"
  | "youtube-channel-playlists"
  | "youtube-channel-search"
  | "youtube-channel-shorts"
  | "youtube-channel-videos"
  | "youtube-comments"
  | "youtube-playlist"
  | "youtube-profile"
  | "youtube-search"
  | "youtube-suggest"
  | "youtube-tag"
  | "youtube-transcript"
  | "youtube-transcript-languages"
  | "youtube-video";

export declare const OperationIds: Readonly<{
  YoutubeCaptions: "youtube-captions";
  YoutubeChannelPlaylists: "youtube-channel-playlists";
  YoutubeChannelSearch: "youtube-channel-search";
  YoutubeChannelShorts: "youtube-channel-shorts";
  YoutubeChannelVideos: "youtube-channel-videos";
  YoutubeComments: "youtube-comments";
  YoutubePlaylist: "youtube-playlist";
  YoutubeProfile: "youtube-profile";
  YoutubeSearch: "youtube-search";
  YoutubeSuggest: "youtube-suggest";
  YoutubeTag: "youtube-tag";
  YoutubeTranscript: "youtube-transcript";
  YoutubeTranscriptLanguages: "youtube-transcript-languages";
  YoutubeVideo: "youtube-video";
}>;
