// Code generated by the Crawlora platform SDK generator. DO NOT EDIT.

package youtube

import (
	"context"
	"sort"
)

type parameterDefinition struct {
	Name             string
	In               string
	Type             string
	CollectionFormat string
	Required         bool
	Enum             []string
}

type operationDefinition struct {
	Method      string
	Path        string
	PathParams  []string
	QueryParams []parameterDefinition
	Produces    []string
	Security    []string
}

var operations = map[string]operationDefinition{
	"youtube-captions":             operationDefinition{Method: "GET", Path: "/youtube/captions/{id}", PathParams: []string{"id"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "lang", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"youtube-channel-playlists":    operationDefinition{Method: "GET", Path: "/youtube/channel/{id}/playlists", PathParams: []string{"id"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "continuation_token", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"youtube-channel-search":       operationDefinition{Method: "GET", Path: "/youtube/channel/{id}/search", PathParams: []string{"id"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "q", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "continuation_token", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"youtube-channel-shorts":       operationDefinition{Method: "GET", Path: "/youtube/channel/{id}/shorts", PathParams: []string{"id"}, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"youtube-channel-videos":       operationDefinition{Method: "GET", Path: "/youtube/channel/{id}/videos", PathParams: []string{"id"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "continuation_token", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"youtube-comments":             operationDefinition{Method: "GET", Path: "/youtube/comments/{id}", PathParams: []string{"id"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "continuation_token", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"youtube-playlist":             operationDefinition{Method: "GET", Path: "/youtube/playlist/{id}", PathParams: []string{"id"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "continuation_token", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"youtube-profile":              operationDefinition{Method: "GET", Path: "/youtube/profile/{id}", PathParams: []string{"id"}, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"youtube-search":               operationDefinition{Method: "GET", Path: "/youtube/search", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "q", In: "query", Type: "string"}, parameterDefinition{Name: "search_query", In: "query", Type: "string"}, parameterDefinition{Name: "continuation_token", In: "query", Type: "string"}, parameterDefinition{Name: "type", In: "query", Type: "string", Enum: []string{"video", "shorts", "channel", "playlist", "movie"}}, parameterDefinition{Name: "sort_by", In: "query", Type: "string", Enum: []string{"relevance", "upload_date", "view_count", "popularity", "rating"}}, parameterDefinition{Name: "upload_date", In: "query", Type: "string", Enum: []string{"last_hour", "today", "this_week", "this_month", "this_year"}}, parameterDefinition{Name: "duration", In: "query", Type: "string", Enum: []string{"under_3_minutes", "three_to_20_minutes", "over_20_minutes", "under_3", "three_to_20", "over_20", "short", "medium", "long"}}, parameterDefinition{Name: "features", In: "query", Type: "string"}, parameterDefinition{Name: "hl", In: "query", Type: "string"}, parameterDefinition{Name: "gl", In: "query", Type: "string"}, parameterDefinition{Name: "params", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"youtube-suggest":              operationDefinition{Method: "GET", Path: "/youtube/suggest", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "q", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "count", In: "query", Type: "integer"}, parameterDefinition{Name: "hl", In: "query", Type: "string"}, parameterDefinition{Name: "gl", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"youtube-tag":                  operationDefinition{Method: "GET", Path: "/youtube/tag/{tag}", PathParams: []string{"tag"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "type", In: "query", Type: "string", Enum: []string{"all", "shorts"}}, parameterDefinition{Name: "continuation_token", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"youtube-transcript":           operationDefinition{Method: "GET", Path: "/youtube/transcript/{id}", PathParams: []string{"id"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "lang", In: "query", Type: "string"}, parameterDefinition{Name: "translate_to", In: "query", Type: "string"}, parameterDefinition{Name: "format", In: "query", Type: "string", Enum: []string{"json", "text", "srt", "vtt"}}, parameterDefinition{Name: "timestamps", In: "query", Type: "boolean"}}, Produces: []string{"application/json", "text/plain"}, Security: []string{"ApiKeyAuth"}},
	"youtube-transcript-languages": operationDefinition{Method: "GET", Path: "/youtube/transcript/{id}/languages", PathParams: []string{"id"}, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"youtube-video":                operationDefinition{Method: "GET", Path: "/youtube/video/{id}", PathParams: []string{"id"}, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
}

// OperationCount reports how many selected-platform operations this module exposes.
const OperationCount = 14

// OperationIDs returns the selected operation IDs in stable sorted order.
func OperationIDs() []string {
	ids := make([]string, 0, len(operations))
	for id := range operations {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

// Captions calls the youtube-captions operation.
func (c *Client) Captions(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-captions", params)
}

// ChannelPlaylists calls the youtube-channel-playlists operation.
func (c *Client) ChannelPlaylists(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-channel-playlists", params)
}

// ChannelSearch calls the youtube-channel-search operation.
func (c *Client) ChannelSearch(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-channel-search", params)
}

// ChannelShorts calls the youtube-channel-shorts operation.
func (c *Client) ChannelShorts(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-channel-shorts", params)
}

// ChannelVideos calls the youtube-channel-videos operation.
func (c *Client) ChannelVideos(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-channel-videos", params)
}

// Comments calls the youtube-comments operation.
func (c *Client) Comments(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-comments", params)
}

// Playlist calls the youtube-playlist operation.
func (c *Client) Playlist(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-playlist", params)
}

// Profile calls the youtube-profile operation.
func (c *Client) Profile(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-profile", params)
}

// Search calls the youtube-search operation.
func (c *Client) Search(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-search", params)
}

// Suggest calls the youtube-suggest operation.
func (c *Client) Suggest(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-suggest", params)
}

// Tag calls the youtube-tag operation.
func (c *Client) Tag(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-tag", params)
}

// Transcript calls the youtube-transcript operation.
func (c *Client) Transcript(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-transcript", params)
}

// TranscriptLanguages calls the youtube-transcript-languages operation.
func (c *Client) TranscriptLanguages(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-transcript-languages", params)
}

// Video calls the youtube-video operation.
func (c *Client) Video(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "youtube-video", params)
}
