"""Emit focused Python packages for Crawlora's hosted API clients."""

from __future__ import annotations

import pprint
import shutil
import sys
from pathlib import Path
from typing import Any
from urllib.parse import quote, urlencode


def _load_helpers(assets: Path):
    assets = assets.resolve()
    if str(assets) not in sys.path:
        sys.path.insert(0, str(assets))
    import python_generator as generator
    from _sdkgen import core

    return core, generator


def _user_agent(config: dict[str, Any]) -> str:
    return f"crawlora-{config['platform']}-python/{config['version']}"


def _module_init(config: dict[str, Any]) -> str:
    class_name = config["class_name"]
    async_class = config["async_class_name"]
    return f'''"""Typed {config['display_name']} client for the Crawlora hosted API."""

from .platform import {class_name}, {async_class}
from .client import CrawloraClientError, CrawloraError, CrawloraNetworkError, CrawloraServerError
from .operations import OPERATION_COUNT, OPERATION_IDS, PLATFORM

Client = {class_name}
AsyncClient = {async_class}
__version__ = {config['version']!r}
DISPLAY_NAME = {config['display_name']!r}
PLATFORM = {config['platform']!r}
CONTRACT_REVISION = {config['contract_revision']!r}

__all__ = [
    "{class_name}", "{async_class}", "Client", "AsyncClient",
    "CrawloraError", "CrawloraClientError", "CrawloraServerError", "CrawloraNetworkError",
    "DISPLAY_NAME", "PLATFORM", "CONTRACT_REVISION", "OPERATION_COUNT", "OPERATION_IDS", "__version__",
]
'''


def _platform_code(config: dict[str, Any], model: Any) -> str:
    class_name = config["class_name"]
    async_class = config["async_class_name"]
    ua = _user_agent(config)
    methods = [(group, method, operation_id) for group, entries in model.groups.items() for method, operation_id in entries.items()]
    lines = [
        '"""Platform-specific convenience clients."""',
        "from __future__ import annotations",
        "from typing import Any",
        "from .client import CrawloraClient",
        "from .async_client import AsyncCrawloraClient",
        "",
        f"class {class_name}(CrawloraClient):",
        f"    \"\"\"Synchronous {config['display_name']} API client.\"\"\"",
        "    def __init__(self, *args: Any, **kwargs: Any) -> None:",
        f"        kwargs.setdefault('user_agent', {ua!r})",
        "        super().__init__(*args, **kwargs)",
        "",
    ]
    if not methods:
        lines.append("    pass")
    for _group, method, operation_id in methods:
        lines.extend([
            f"    def {method}(self, **params: Any) -> Any:",
            "        response_type = params.pop('_response_type', 'auto')",
            "        timeout = params.pop('_timeout', None)",
            "        headers = params.pop('_headers', None)",
            f"        return self.request({operation_id!r}, params, response_type=response_type, timeout=timeout, headers=headers)",
            "",
        ])
    lines.extend([
        f"class {async_class}(AsyncCrawloraClient):",
        f"    \"\"\"Asynchronous {config['display_name']} API client.\"\"\"",
        "    def __init__(self, *args: Any, **kwargs: Any) -> None:",
        f"        kwargs.setdefault('user_agent', {ua!r})",
        "        super().__init__(*args, **kwargs)",
        "",
    ])
    if not methods:
        lines.append("    pass")
    for _group, method, operation_id in methods:
        lines.extend([
            f"    async def {method}(self, **params: Any) -> Any:",
            "        response_type = params.pop('_response_type', 'auto')",
            "        timeout = params.pop('_timeout', None)",
            "        headers = params.pop('_headers', None)",
            f"        return await self.request({operation_id!r}, params, response_type=response_type, timeout=timeout, headers=headers)",
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"


def _operations_module(config: dict[str, Any], model: Any) -> str:
    from _sdkgen import core

    op_ids = sorted(model.meta)
    constants: list[str] = []
    used: set[str] = set()
    for operation_id in op_ids:
        value = core.type_name(model.meta[operation_id]["type_base"])
        constant = "_".join(core.words(value)).upper() or "OPERATION"
        base = constant
        suffix = 2
        while constant in used:
            constant = f"{base}_{suffix}"
            suffix += 1
        used.add(constant)
        constants.append(f"    {constant} = {operation_id!r}")
    return (
        "# Generated by scripts/generate.py. Do not edit manually.\n"
        f"PLATFORM = {config['platform']!r}\n"
        f"OPERATION_COUNT = {model.operation_count}\n"
        f"OPERATION_IDS = {tuple(op_ids)!r}\n\n"
        f"OPERATIONS = {pprint.pformat(model.operations, sort_dicts=True, width=120)}\n\n"
        f"GROUPS = {pprint.pformat(model.groups, sort_dicts=True, width=120)}\n\n"
        "class OperationId:\n"
        + ("\n".join(constants) if constants else "    pass")
        + "\n"
    )


def _platform_stub(config: dict[str, Any], model: Any, assets: Path) -> str:
    """Add explicit autocomplete signatures to the generic runtime stubs."""
    core, generator = _load_helpers(assets)
    declarations = generator.stub_declarations(model)
    text_responses: dict[str, tuple[str, list[str]]] = {}
    for operation_id, operation in model.operations.items():
        if "text/plain" not in operation.get("produces", []):
            continue
        format_param = next((param for param in model.meta[operation_id]["params"] if param["name"] == "format"), None)
        text_formats = [str(value) for value in (format_param or {}).get("enum", []) if str(value).lower() not in {"json", "application/json"}]
        if text_formats:
            text_responses[operation_id] = (model.meta[operation_id]["type_base"], text_formats)

    def append_facade_signatures(target: list[str], method: str, operation_id: str, *, asynchronous: bool = False) -> None:
        base = model.meta[operation_id]["type_base"]
        prefix = "async " if asynchronous else ""
        target += [
            "    @overload",
            f"    {prefix}def {method}(self, **params: Unpack[{base}StreamParams]) -> BinaryIO: ...",
            "    @overload",
            f"    {prefix}def {method}(self, **params: Unpack[{base}TextResponseParams]) -> str: ...",
        ]
        if operation_id in text_responses:
            target += [
                "    @overload",
                f"    {prefix}def {method}(self, **params: Unpack[{base}TextParams]) -> str: ...",
            ]
        target += [
            "    @overload",
            f"    {prefix}def {method}(self, **params: Unpack[{base}Params]) -> {base}Response: ...",
        ]

    def append_response_options(target: list[str], operation_id: str) -> None:
        base = model.meta[operation_id]["type_base"]
        params = model.meta[operation_id]["params"]
        for mode, literal, response in (("TextResponseParams", "text", "str"), ("StreamParams", "stream", "BinaryIO")):
            fields = {
                "_response_type": f"Required[Literal[{literal!r}]]",
                "_timeout": "NotRequired[float]",
                "_headers": "NotRequired[Mapping[str, str]]",
            }
            for param in params:
                if param.get("in") == "body":
                    typ = f"{base}Body"
                else:
                    typ = generator.py_type(param)
                wrapper = "Required" if param.get("required") else "NotRequired"
                fields[param["name"]] = f"{wrapper}[{typ}]"
            target += ["", f"{base}{mode} = TypedDict({(base + mode)!r}, {{"]
            target.extend(f"    {key!r}: {typ}," for key, typ in fields.items())
            target.append("}, total=False)")

    lines = [
        declarations,
        "from typing import BinaryIO",
        "",
        "class AsyncCrawloraClient:",
        "    def __init__(self, **kwargs: Any) -> None: ...",
        "    async def aclose(self) -> None: ...",
        "    async def __aenter__(self) -> AsyncCrawloraClient: ...",
        "    async def __aexit__(self, *exc: Any) -> None: ...",
        "    async def request(self, operation_id: str, params: Mapping[str, Any] | None = ..., *, response_type: ResponseType = ..., timeout: float | None = ..., headers: Mapping[str, str] | None = ..., retries: int | None = ..., retry_predicate: Callable[[int, BaseException | None], bool] | None = ...) -> Any: ...",
        "",
        f"class {config['class_name']}(CrawloraClient):",
    ]
    lines.append(f"    def __enter__(self) -> {config['class_name']}: ...")
    for group_name in model.groups:
        lines.append(f"    {group_name}: {core.type_name(group_name, 'group')}")
    methods = [(method, operation_id) for entries in model.groups.values() for method, operation_id in entries.items()]
    if not methods:
        lines.append("    pass")
    for method, operation_id in methods:
        append_facade_signatures(lines, method, operation_id)
    lines += ["", f"class {config['async_class_name']}(AsyncCrawloraClient):"]
    lines.append(f"    async def __aenter__(self) -> {config['async_class_name']}: ...")
    for group_name in model.groups:
        lines.append(f"    {group_name}: _Async{core.type_name(group_name, 'group')}")
    for method, operation_id in methods:
        append_facade_signatures(lines, method, operation_id, asynchronous=True)
    for group_name, entries in model.groups.items():
        lines += ["", f"class _Async{core.type_name(group_name, 'group')}:"]
        for method, operation_id in entries.items():
            append_facade_signatures(lines, method, operation_id, asynchronous=True)
    for operation_id, (base, formats) in text_responses.items():
        fields = {
            "_response_type": "NotRequired[ResponseType]",
            "_timeout": "NotRequired[float]",
            "_headers": "NotRequired[Mapping[str, str]]",
        }
        for param in model.meta[operation_id]["params"]:
            if param["name"] == "format":
                fields[param["name"]] = f"Required[{generator.py_enum_type(formats)}]"
            else:
                typ = generator.py_type(param)
                wrapper = "Required" if param.get("required") else "NotRequired"
                fields[param["name"]] = f"{wrapper}[{typ}]"
        lines += ["", f"{base}TextParams = TypedDict({(base + 'TextParams')!r}, {{"]
        lines.extend(f"    {key!r}: {typ}," for key, typ in fields.items())
        lines.append("}, total=False)")
    for operation_id in model.meta:
        append_response_options(lines, operation_id)
    return "\n".join(lines) + "\n"


def _test_fixture(model: Any) -> dict[str, Any]:
    """Choose a mocked GET operation that exercises routing and query encoding."""
    candidates = []
    for operation_id, operation in model.operations.items():
        if operation["method"] != "GET" or not operation.get("queryParams"):
            continue
        security = operation.get("security", [])
        score = 4 + 2 * bool(operation.get("pathParams")) + 3 * ("ApiKeyAuth" in security)
        candidates.append((score, operation_id, operation, model.meta[operation_id]["params"]))
    if not candidates:
        raise ValueError("platform spec must include a GET operation with query parameters for generated tests")
    _score, operation_id, operation, params = max(candidates, key=lambda item: (item[0], item[1]))

    def sample(param: dict[str, Any]) -> Any:
        enum = param.get("enum") or []
        if enum:
            return enum[0]
        typ = param.get("type")
        if typ == "array":
            item = param.get("items", {})
            item_enum = item.get("enum") or []
            return [item_enum[0], item_enum[-1]] if item_enum else ["first", "second"]
        if typ == "boolean":
            return True
        if typ == "integer":
            return 7
        if typ == "number":
            return 7.5
        return "test value"

    values: dict[str, Any] = {}
    for param in params:
        if param.get("in") == "path" or (param.get("in") == "query" and param.get("required")):
            values[param["name"]] = sample(param)
    optional_query = next((param for param in params if param.get("in") == "query" and param["name"] not in values), None)
    if optional_query is not None:
        values[optional_query["name"]] = sample(optional_query)

    path = operation["path"]
    for name in operation.get("pathParams", []):
        path = path.replace("{" + name + "}", quote(str(values[name]), safe=""))
    query: list[tuple[str, str]] = []
    for param in operation.get("queryParams", []):
        name = param["name"]
        if name not in values:
            continue
        value = values[name]
        items = value if isinstance(value, (list, tuple)) else [value]
        query.extend((name, _stringify_query_value(item)) for item in items)
    expected_url = "https://api.example.test" + path
    if query:
        expected_url += "?" + urlencode(query)
    return {
        "test_operation_id": repr(operation_id),
        "test_method_name": repr(next(method for method, oid in model.groups[model.meta[operation_id]["group"]].items() if oid == operation_id)),
        "test_group_name": repr(model.meta[operation_id]["group"]),
        "test_params": pprint.pformat(values, sort_dicts=True),
        "test_url": repr(expected_url),
        "test_has_api_key": "ApiKeyAuth" in operation.get("security", []),
    }


def _stringify_query_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def emit(root: Path, config: dict[str, Any], spec: dict[str, Any], assets: Path) -> None:
    """Write a typed, installable platform package into ``root/python``."""
    core, generator = _load_helpers(assets)
    # The vendored helper is shared with the main Python SDK and centralizes
    # naming and all OpenAPI-to-Python type mapping.
    model = core.build_model(spec, generator.POLICY)
    package = root / "python" / config["module_name"]
    package.mkdir(parents=True, exist_ok=True)
    template_root = Path(__file__).resolve().parent / "templates" / "python"

    for source, target in (
        (assets / "python" / "client.py", package / "client.py"),
        (assets / "python" / "async_client.py", package / "async_client.py"),
        (assets / "python" / "_transport_sync.py", package / "_transport_sync.py"),
        (assets / "python" / "_pagination.py", package / "_pagination.py"),
    ):
        shutil.copyfile(source, target)

    (package / "operations.py").write_text(_operations_module(config, model), encoding="utf-8")
    (package / "platform.py").write_text(_platform_code(config, model), encoding="utf-8")
    (package / "platform.pyi").write_text(_platform_stub(config, model, assets), encoding="utf-8")
    (package / "__init__.py").write_text(_module_init(config), encoding="utf-8")
    (package / "__init__.pyi").write_text(
        f"from .platform import {config['class_name']} as {config['class_name']}\n"
        f"from .platform import {config['async_class_name']} as {config['async_class_name']}\n"
        f"Client = {config['class_name']}\nAsyncClient = {config['async_class_name']}\n"
        "from .client import CrawloraClientError as CrawloraClientError, CrawloraError as CrawloraError, CrawloraNetworkError as CrawloraNetworkError, CrawloraServerError as CrawloraServerError\n"
        "from .operations import OPERATION_COUNT as OPERATION_COUNT, OPERATION_IDS as OPERATION_IDS, PLATFORM as PLATFORM\n"
        f"__version__: str\nDISPLAY_NAME: str\nCONTRACT_REVISION: str\n"
        f"__all__ = {[config['class_name'], config['async_class_name'], 'Client', 'AsyncClient', 'CrawloraError', 'CrawloraClientError', 'CrawloraServerError', 'CrawloraNetworkError', 'DISPLAY_NAME', 'PLATFORM', 'CONTRACT_REVISION', 'OPERATION_COUNT', 'OPERATION_IDS', '__version__']!r}\n",
        encoding="utf-8",
    )
    (package / "py.typed").write_text("", encoding="utf-8")

    pyproject = (template_root / "pyproject.toml.tpl").read_text(encoding="utf-8")
    for key, value in config.items():
        pyproject = pyproject.replace("{{" + key.upper() + "}}", str(value))
    (root / "python" / "pyproject.toml").write_text(pyproject, encoding="utf-8")
    license_text = (template_root / "LICENSE.tpl").read_text(encoding="utf-8")
    (root / "python" / "LICENSE").write_text(license_text, encoding="utf-8")
    tests_root = root / "python" / "tests"
    tests_root.mkdir(parents=True, exist_ok=True)
    (tests_root / "__init__.py").write_text("", encoding="utf-8")
    package_test = (template_root / "tests" / "test_package.py.tpl").read_text(encoding="utf-8")
    for key, value in {**config, **_test_fixture(model)}.items():
        package_test = package_test.replace("{{" + key.upper() + "}}", str(value))
    (tests_root / "test_package.py").write_text(package_test, encoding="utf-8")
    if config["platform"] == "youtube" and "youtube-transcript" in model.meta:
        type_test = (template_root / "tests" / "test_types.py.tpl").read_text(encoding="utf-8")
        for key, value in config.items():
            type_test = type_test.replace("{{" + key.upper() + "}}", str(value))
        (tests_root / "test_types.py").write_text(type_test, encoding="utf-8")
        transcript_test = (template_root / "tests" / "test_transcript.py.tpl").read_text(encoding="utf-8")
        for key, value in config.items():
            transcript_test = transcript_test.replace("{{" + key.upper() + "}}", str(value))
        (tests_root / "test_transcript.py").write_text(transcript_test, encoding="utf-8")
